### ISSUE TITLE
BUILD FAILED - 'module' object has no attribute 'helloworld_sensor_tests'

### ISSUE THREAD

**Issue by larrykooper** [chandulal/airflow-testing#1]
When I ran pyb run_unit_tests I got a message

BUILD FAILED - 'module' object has no attribute 'helloworld_sensor_tests'

**Comment by chandulal** [comment]
Did you check the installed python version?

**Comment by chandulal** [comment]
I have updated $AIRFLOW_HOME path in README file. Also, added one more step in order to fix the test. 

Can you follow all the steps again and let me know.
